# Seed
mode=classic
computer_smart=true
isAuto=false
thinkingTime=2000
delayTime=1000
number_cards=13
rounds.0.players.0.initialcards=11H,2H,9H,13H,2D,4D,5D,12D,1C,3C,10C,11C,12C
rounds.0.players.1.initialcards=1S,2S,3S,4S,5S,6S,7S,8S,9S,13S,12S,10S,11S
players.0.cardsPlayed=
players.1.cardsPlayed=