mode=gin
isAuto=false
computer_smart=true
thinkingTime=50
delayTime=100
number_cards=10
rounds.0.players.0.initialcards=2D,4D,7D,13D,5D,6D,9D,2H,3H,4H
rounds.0.players.1.initialcards=1S,2S,3S,4S,5S,6S,7S,8S,9S,10S
rounds.0.stockpile.cards=12S,3D
# For manual test, so these values are only as guidelines
#rounds.0.players.0.cardsPlayed=
#rounds.0.players.1.cardsPlayed=STOCKPILE-5S,DISCARD-6S-KNOCK